site_name: "My Docs"
site_name: Documentation
site_description: Sample Docs
site_author: Mirantis, Inc.
site_url: "aa"
docs_dir: docs/
repo_name: GitHub
repo_url: 
copyright:
  Copyright &copy; BUILD_YEAR <a href="https://mirantis.com/">Mirantis Inc.</a>
  - All rights reserved.
edit_uri: ""


theme:
  name: material
  version:
    provider: mike
    default: latest

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PrashantR30/mike


plugins:
  - search
  - mermaid2
  - mike
