name: docs

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: ensures tags are fetched

      - name: Get last 2 tags in descending order
        id: get_tags
        run: |
          # Ensure tags are up-to-date (especially if using shallow clones or older commits)
          git fetch --tags

          # Get last two tags matching 'v*'
          last_two_tags=$(git tag --list "v*" --sort=-version:refname | head -n 2)

          # Print them as a single string
          echo "Found tags: $last_two_tags"

          # Convert string to an array by splitting on newlines
          IFS=$'\n' read -r -d '' -a tags_array <<< "$last_two_tags"

          # Loop over the array
          for tag in "${tags_array[@]}"; do
            echo "Processing tag: $tag"
          done

      - name: Configure Git Credentials
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.x

      # - name: Generate Cache ID
      #   run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      # - name: Restore Cache
      #   uses: actions/cache@v4
      #   with:
      #     key: mkdocs-material-${{ env.cache_id }}
      #     path: .cache
      #     restore-keys: |
      #       mkdocs-material-

      # - name: Install Dependencies
      #   run: |
      #     pip install \
      #       mkdocs-material \
      #       mkdocs-mermaid2-plugin \
      #       mike

      # - name: Deploy Docs
      #   run: mkdocs gh-deploy --force
